### ISSUE TITLE
Error: Can't find files

### ISSUE THREAD

**Issue by jamesladd** [Aletheios/v-drag-drop#2]
Thank you for a very useful and simple component.
I have been using v 0.3.0 for a while.
I upgraded to v 1.0.0 and get the following error.

These dependencies were not found:

* @/draggable in ./node_modules/v-drag-drop/src/index.js
* @/droppable in ./node_modules/v-drag-drop/src/index.js

To install them, you can run: npm install --save @/draggable @/droppable

I think there is something not quite right in the package.
Maybe the dist?

**Comment by Aletheios** [comment]
Hi, Thanks for your feedback!

The built files in `dist` should work fine, but the files in `src` required a webpack path alias.

I've removed the alias `@` now which didn't bring any benefit in the setup anyways. Please upgrade to version 1.0.1 and check if it's working now.
